---
# Bring the Stack DOWN
- hosts: loadbalancer
  become: true
  tasks:
    - service: name=nginx state=stopped
  
- hosts: webserver
  become: true
  tasks:
    - service: name=apache2 state=stopped

# Restart mysql
- hosts: database
  become: true
  tasks: 
    - service: name=mysql start=restarted
  
# Bring the Stack UP
- hosts: webserver
  become: true
  tasks:
    - service: name=apache2 state=started

- hosts: loadbalancer
  become: true
  tasks:
    - service: name=nginx state=started